### ISSUE TITLE
Отсутствует индикация действий

### ISSUE THREAD

**Issue by barakuda211** [Palom-Porom/FangsAndSteel#38]
Нажатия на кнопки и указание направления движения никак не обозначаются

**Comment by Palom-Porom** [comment]
Касательно кнопки `Режим Огня` есть пояснение в README, это баг, нужно исправить

Касательно указания направления движения и кнопки `Стоп` - планируется к реализации в процессе одной из ближайших крупных задач (*настройка shift-приказов*)
