### ISSUE TITLE
Поворот камеры неудобный

### ISSUE THREAD

**Issue by caisilus** [Palom-Porom/FangsAndSteel#39]
Возможно, дело в чувствительности или каком-то ускорении, но очень часто она улетает наверх, когда я этого не хочу. Возможно, стоит вообще ограничить её "задирание" наверх (потому что зачем смотреть наверх в стратегии) и сделать настройку чувствительности

Вы не рассматривали вариант вообще с фиксированным ракурсом камеры и возможностью приближать?

**Comment by Palom-Porom** [comment]
Да, мы собираемся несколько более зафиксировать камеру, а именно сделать так, чтобы на WASD камера двигалась, не изменяя своей высоты. Высота же будет в некоторой ограниченной степени меняться с помощью прокрутки колесика мыши
Изначально "задирание" вверх было оставлено на случай, если игрок захочет посмотреть на поле боя под более "кинематографичным" углом. Но затем было введено ограничение по минимальной высоте, отчего смысл такого решения был несколько утерян. Сейчас рассматривается вариант того, чтобы на дальнейших стадиях разработки также ввести "кинематографичный" режим, когда "границы" камеры будут расширяться; в то же время в "стандартном" режиме камеры мы сделаем более фиксированные углы обзора, которые могут понадобиться для игры.
А насчет чувствительности благодарю за фидбек - действительно следует несколько уменьшить её. Сам видимо приноровился и даже не заметил этого :)
