### ISSUE TITLE
Управление камерой ломается

### ISSUE THREAD

**Issue by Tetrergeru** [Palom-Porom/FangsAndSteel#59]
Судя по всему что-то начудили с эйлеровыми углами и анимацией в туториале, потому что сначала всё было прилично, а через пять минут игры камеру стало невероятно колбасить

**Comment by Palom-Porom** [comment]
Колбасить стало после нажатия на кнопку или во время обычного перемещения/вращения на васд/СКМ?

**Comment by Palom-Porom** [comment]
Не смогли воспроизвести
