### ISSUE TITLE
На этапе закупки юнитов есть возможность поставить юнита за пределами выделенной границы

### ISSUE THREAD

**Issue by rypunov** [Palom-Porom/FangsAndSteel#68]
![Снимок экрана 2024-05-18 212255](https://github.com/Palom-Porom/FangsAndSteel/assets/146518314/81b9e803-e681-414b-b741-cb5d87a5cf09)

**Comment by Palom-Porom** [comment]
А как это получилось? Можно поподробнее про то, как достиг этой ошибки

**Comment by rypunov** [comment]
Выбрал юнита в левом верхнем углу. Он появился в центре экрана. Я нажал ЛКМ, он сохранился

**Comment by Palom-Porom** [comment]
Можешь записать пожалуйста видео, я вообще никак не могу повторить этой штуки. Видимо что-то не так делаю
